### ISSUE TITLE
Better handle decoding arrays of values

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/netable#104]
Right now, if you make a request that's meant to return an array of objects, and one of those objects fails to decode, the entire request fails.

This is a little unexpected to me, I would have expected that the array return all of the objects that successfully decoded and just skipped the un-decodable value.

I think we should probably include an option in the config to toggle this behaviour, but it seems useful to atleast offer the choice to users

**Comment by amyoulton** [comment]
@brendanlensink @jenncoop hey! I was just look at this and I believe this is actually completed. It got assigned to me but I am fairly certain that this is the lossy array stuff that brendan was working on before the holidays, which is now live! If I'm correct, the merged PR is [here](https://github.com/steamclock/netable/pull/107).

**Comment by brendanlensink** [comment]
Sure is!
