### ISSUE TITLE
Investigate adding support for some automatic unwrapping of nested objects

### ISSUE THREAD

**Issue by nbrooke** [steamclock/netable#68]
A thing that happens occasionally is a JSON API giving back the object we actually care about inside a single level wrapper, so something like 

```
// Object we care about
struct Foo: Codable {
    let bar: Int
    let baz: Int
}

//JSON
{
    "foo": {
        "bar": 1,
        "baz": 2
    }
}
```

The finalization support can deal with this pretty easily, but it does require a moderate amount of boilerplate for how simple the unwrapping is (creating a single use, single property struct for the response, write a trivial unwrapping `finalize` function). It'd be nice if there was some way to do a minimalist specification that this is going on rather than having to add that boilerplate manually, something along the lines of

```
struct FooRequest: Request {
     typealias RawResource = SmartUnwrap<Foo>
     typealias FinalizedResource = Foo

    //...
}
```
with no need to implement finalize, because there's an `extension Request where RawResource == SmartUnwrap` somewhere that implements it.

I don't THINK this is possible in this form, because even with a manual `Decodable` initializer on `SmartUnwrap` I don't think it's possible to pull out a property without knowing its coding key (and there's no way to specify the key in a construction like this), but maybe there is some way to make this work, it might be worth at least a bit of investigation.

**Comment by brendanlensink** [comment]
It might be worth seeing if any of the other networking libraries in Swift have a solution for this.
