### ISSUE TITLE
Replace current example project with a more modern SwiftUI-friendly example

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/netable#86]
### High Level Goals

The example project should be as small and as simple as possible, while still providing examples for all the features of Netable listed below.

What the app actually _does_ isn't super important, but usually some kind of Calendar/TODO/blog app makes the most sense as it's familiar to most people.

The goal is that a new user should be able to read briefly about a feature in the README, and then if they need extra guidance be able to refer to the example project for a more detailed implementation of the feature.

### Examples to Include
There's a good chance I missed some stuff here, but this definitely seems like a good start. Also note not _every_ example needs to be separate, as long as it's clear what's being demo'd each time.

#### Creating Netable Instances
- [ ] Default, just provide a baseURL
- [ ] Set some config options
- [ ] Set custom log destination
- [ ] Set a custom retry configuration

#### Requests

- [ ] Super basic "go get a JSON and return it" using async/await
- [ ] Basic example using Combine
- [ ] SmartUnwrap (with custom unwrap key)
- [ ] Custom `Finalize`
- [ ] Request with custom JSON en/decoding strategies
- [ ] Redacting/unredacting parameters
- [ ] GraphQL Query
- [ ] GraphQL Mutation
- [ ] Cancelling tasks
- [ ] Retrying a request

### Handling Errors

- [ ] requestFailureDelegate
- [ ] requestFailurePublisher
- [ ] try/catch
- [ ] FallbackResource

Stretch goals:
Since netable is now an actor and immutable, we'll want to show how you do something simple like logging in without auth, then providing an auth token for all subsequent requests

**Comment by brendanlensink** [comment]
@Amy it's up to you if you want to modify the existing project, or start from a clean slate for this. Either way you'll want to branch off of https://github.com/steamclock/netable/pull/99 to get started if it isn't merged into main yet.

**Comment by amyoulton** [comment]
@brendanlensink #99 is merged so am I just branching off of main now?

**Comment by brendanlensink** [comment]
That's correct 🚀

**Comment by amyoulton** [comment]
Do I get to make it pretty 🤔 I realise that's not like the core priority, but 🙃

**Comment by amyoulton** [comment]
This is completed and merged via #105!
