### ISSUE TITLE
Investigate adding support for GraphQL requests

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/netable#96]
[This article](https://joinhandshake.com/blog/our-team/graphql-on-ios/) outlines how a team built their own codebase on top of Alamofire to query GraphQL, which seems like something that would be kind of neat for Netable to support.

**Comment by jenncoop** [comment]
It seems worth doing a mini investigation into this to see what's involved

**Comment by brendanlensink** [comment]
I think this would be really useful, and potentially not super difficult given that GraphQL requests are kind of just POST requests with a weird body.

I think the biggest problem we'd want to tackle, or atleast have a good idea of what we want to do with, ahead of time is how we want to handle defining the requests.

In the article above they still use `.graphQL` requests that are shared with other platforms, and AFAICT generated outside of the scope of the project. This sort of makes sense, as one of the biggest features Apollo provides is through code generation and automatically downloading the schema for GQL endpoints.

I sort of wonder how difficult it would be to write a wrapper that lets you skip writing the `.graphql` file, and instead uses the model you're expecting to be returned to generate that body automatically.

You would lose the ability to share code between other services using the same requests this way, but since you'll need to write the models anyways maybe this isn't really a big loss?
